# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.1
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/home/linsun/Xilinx/Vivado_HLS/2017.1/../../Vivado/2017.1/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcvu9p-fsgd2104-3-e-es1 ../xilinx_com_hls_sum_io_1_0.zip
